config/routes.rb
Rails.application.routes.draw do
  root to: 'sites#index'

  post 'omniauth/callback'       => 'omniauth#callback', as: :omniauth
  get '/auth/:provider/callback' => 'omniauth#callback'

  delete '/signout' => 'sessions#destroy', as: :sign_out

  get '/pages/about' => 'pages#about', as: 'about_page'
  get '/pages/login' => 'pages#login', as: 'login_page'

  resources :sites do
    collection do
      get :all
    end
  end

  get '/sites/daily/:day' => 'sites#daily'

  resource :session
  resource :profile

  if Rails.env.development?
    get '/backdoor(/:id)' => 'sessions#backdoor'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :require_user

  def show
  end

  def edit
  end

  def update
    if current_user.update_attributes(profile_params)
      redirect_to profile_path, notice: 'Your profile was updated.'
    else
      render action: :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to about_page_path, notice: 'Your account here has been deleted.'
  end

  private

  def profile_params
    params.require(:user).permit(
      :name,
      :time_zone
    )
  end
end

app/views/profiles/edit.html.erb
<h2>Edit profile</h2>

<%= form_for current_user, url: profile_path, html: {class: 'form-horizontal'} do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited your profile from being saved:</h2>

      <ul>
        <% current_user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-xs-2' %>
    <div class="col-xs-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :time_zone, class: 'control-label col-xs-2' %>
    <div class="col-xs-10">
      <%= f.time_zone_select :time_zone, nil, {}, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-xs-offset-2 col-xs-10">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<%= link_to "Go to your sites", sites_path,   class: 'btn btn-default' %>
<%= link_to "Show profile",     profile_path, class: 'btn btn-default' %>

app/views/profiles/show.html.erb
<h2>Your profile</h2>

<p>Name:      <strong><%= current_user.name %></strong></p>
<p>Time zone: <strong><%= current_user.time_zone %></strong></p>

<p>
  <h2>Registrations:</h2>
  <ul>
    <% current_user.registrations.each do |registration| %>
      <li><%= registration.provider %>: <strong><%= registration.uid %></strong></li>
    <% end %>
  </ul>

  <div>
    <%= link_to 'Add twitter registration', '/auth/twitter' %>
  </div>
</p>

<%= link_to "Go to your sites", sites_path, class: 'btn btn-default' %>
<%= link_to "Edit profile", edit_profile_path, class: 'btn btn-default' %>
<%= link_to "Delete account", profile_path, class: 'btn btn-danger', data: {
  confirm: 'Are you really, really sure you want to delete your account?',
  method: :delete
} %>