config/routes.rb
Rails.application.routes.draw do
  root to: 'sites#index'

  post 'omniauth/callback'       => 'omniauth#callback', as: :omniauth
  get '/auth/:provider/callback' => 'omniauth#callback'

  delete '/signout' => 'sessions#destroy', as: :sign_out

  get '/pages/about' => 'pages#about', as: 'about_page'
  get '/pages/login' => 'pages#login', as: 'login_page'

  resources :sites do
    collection do
      get :all
    end
  end

  get '/sites/daily/:day' => 'sites#daily'

  resource :session
  resource :profile

  if Rails.env.development?
    get '/backdoor(/:id)' => 'sessions#backdoor'
  end
end

app/views/pages/about.html.erb
<p>
  This is a very simple site with the purpose of remembering links to places
  you visit on a regular basis. You can enter a site and which days of the week
  you want to check it. Every day, you can come back here and see a list of all
  your sites for today.
</p>

<p>
  If you'd like to try it out, just sign in below and you can destroy your
  account whenever you like.
</p>

<%= render 'shared/logins' %>

<p>
  If you have any problems with it or want to see more features here, you can
  write me an email at <%= andrews_email %>.

  <br />

  Or, better yet, file an issue on the
  <%= link_to 'github issue tracker', 'https://github.com/AndrewRadev/daily-sites/issues' %>.
</p>

app/views/pages/login.html.erb
<h2>Hello, there.</h2>

<%= render 'shared/logins' %>

<p class="pull-right">
  <%= link_to 'What is this about?', about_page_path %>
</p>