config/routes.rb
Rails.application.routes.draw do
  root to: 'sites#index'

  post 'omniauth/callback'       => 'omniauth#callback', as: :omniauth
  get '/auth/:provider/callback' => 'omniauth#callback'

  delete '/signout' => 'sessions#destroy', as: :sign_out

  get '/pages/about' => 'pages#about', as: 'about_page'
  get '/pages/login' => 'pages#login', as: 'login_page'

  resources :sites do
    collection do
      get :all
    end
  end

  get '/sites/daily/:day' => 'sites#daily'

  resource :session
  resource :profile

  if Rails.env.development?
    get '/backdoor(/:id)' => 'sessions#backdoor'
  end
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user

  validates :title, :url, :user, presence: true
  validates :url, format: URI.regexp(['http', 'https', 'file'])

  Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday = (1 .. 7).to_a

  DayNames = {
    Monday    => 'monday',
    Tuesday   => 'tuesday',
    Wednesday => 'wednesday',
    Thursday  => 'thursday',
    Friday    => 'friday',
    Saturday  => 'saturday',
    Sunday    => 'sunday',
  }

  # TODO work around the "0" and "1" that come from the checkbox
  DayNames.each do |day, day_name|
    define_method "#{day_name}=" do |yes|
      if yes.to_i > 0
        # TODO: It needs to be initialized here, not sure why
        self.days ||= Set.new
        self.days << day
      else
        self.days.delete(day)
      end
    end

    define_method day_name do
      self.days.include? day
    end
  end

  serialize :days

  def days
    super or (self.days = Set.new)
  end

  def days=(v)
    super(v.try(:to_set))
  end

  def day_names
    if days == [Saturday, Sunday].to_set
      'Weekends'
    elsif days == (Monday .. Friday).to_set
      'Weekdays'
    elsif days == (Monday .. Sunday).to_set
      'Every day'
    else
      days.to_a.sort.map { |d| DayNames[d].capitalize }.to_sentence
    end
  end

  def url_root
    "#{uri.scheme}://#{uri.host}"
  end

  def uri
    @uri ||= URI.parse(url)
  end

  class << self
    def day_names_for_select
      DayNames.invert
    end

    def for_day(day)
      Site.order('title').all.select do |s|
        s.days.include? day
      end
    end

    def for_time(time)
      # wday starts on Sunday
      if time.wday == 0
        for_day(7)
      else
        for_day(time.wday)
      end
    end
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :require_user

  def index
    @sites = current_user.sites.for_time(current_time)
    @title = "Sites for today, #{current_time.to_date.to_s(:long)}"
  end

  def all
    @sites = current_user.sites
    @title = "All sites"
    render :index
  end

  def daily
    day    = params[:day].to_i
    @sites = current_user.sites.for_day(day)
    @title = "Sites for #{Site::DayNames[day]}"

    render :index
  end

  def new
    @site = Site.new
  end

  def edit
    @site = Site.find(params[:id])
  end

  def create
    @site      = Site.new(site_params)
    @site.user = current_user

    if @site.save
      redirect_to root_path, :notice => 'Site was successfully created.'
    else
      render :action => :new
    end
  end

  def update
    @site = Site.find(params[:id])

    if @site.update_attributes(site_params)
      redirect_to root_path, :notice => 'Site was successfully updated.'
    else
      render :action => :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    redirect_to root_path
  end

  private

  def site_params
    params.require(:site).permit(
      :url, :title,
      :monday, :tuesday, :wednesday, :thursday, :friday,
      :saturday, :sunday
    )
  end
end

app/views/sites/_form.html.erb
<%= form_for(@site, html: {class: 'form-horizontal'}) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
        <% @site.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label col-xs-1' %>
    <div class="col-xs-11">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :url, class: 'control-label col-xs-1' %>
    <div class="col-xs-11">
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :days, class: 'control-label col-xs-1' %>

    <div class="checkbox col-xs-11">
      <label><%= f.check_box :monday    %> Monday    </label><br>
      <label><%= f.check_box :tuesday   %> Tuesday   </label><br>
      <label><%= f.check_box :wednesday %> Wednesday </label><br>
      <label><%= f.check_box :thursday  %> Thursday  </label><br>
      <label><%= f.check_box :friday    %> Friday    </label><br>
      <label><%= f.check_box :saturday  %> Saturday  </label><br>
      <label><%= f.check_box :sunday    %> Sunday    </label><br>
    </div>
  </div>

  <div class="form-group">
    <div class="col-xs-offset-1 col-xs-11">
      <%= f.submit class: 'btn btn-primary' %>
      <% if @site.persisted? %>
        <%= link_to 'Show', @site.url, target: '_newtab', class: 'btn btn-default' %>
      <% end %>
      <%= link_to 'Back', sites_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h2>Editing site</h2>

<%= render 'form' %>

app/views/sites/index.html.erb
<h2>
  <%= @title %>
  <%= link_to 'Open all links', '#', id: 'open-links', class: 'btn btn-primary' %>
</h2>

<div class="actions">
  <%= link_to 'New site',        new_site_path,  class: 'btn btn-default' %>
  <%= link_to 'Sites for today', sites_path,     class: 'btn btn-default' %>
  <%= link_to 'All sites',       all_sites_path, class: 'btn btn-default' %>

  Or, show sites for

  <div class="dropdown day-select">
    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
      a particular day
      <span class="caret"></span>
    </button>

    <ul class="dropdown-menu">
      <% Site.day_names_for_select.each do |name, id| %>
        <li><a href="#" data-id="<%= id %>"><%= name.titleize %></a></li>
      <% end %>
    </ul>
  </div>
</div>

<table class="table table-hover">
  <tr>
    <th>Site</th>
    <th>Days</th>
    <th></th>
  </tr>

  <% @sites.each do |site| %>
    <tr>
      <td class="site">
        <%= favicon site %>
        <%= link_to site.title, site.url, target: '_newtab', class: 'js-link' %>
      </td>
      <td><%= site.day_names %></td>
      <td align="center">
        <%= link_to 'Edit', edit_site_path(site), class: 'btn btn-default' %>
        <%= link_to 'Remove', site, class: 'btn btn-danger', data: {
          confirm: 'Are you sure?',
          method: :delete,
        } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/sites/new.html.erb
<h2>New site</h2>

<%= render 'form' %>