config/routes.rb
Rails.application.routes.draw do
  root to: 'sites#index'

  post 'omniauth/callback'       => 'omniauth#callback', as: :omniauth
  get '/auth/:provider/callback' => 'omniauth#callback'

  delete '/signout' => 'sessions#destroy', as: :sign_out

  get '/pages/about' => 'pages#about', as: 'about_page'
  get '/pages/login' => 'pages#login', as: 'login_page'

  resources :sites do
    collection do
      get :all
    end
  end

  get '/sites/daily/:day' => 'sites#daily'

  resource :session
  resource :profile

  if Rails.env.development?
    get '/backdoor(/:id)' => 'sessions#backdoor'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Daily Sites</title>

    <%= stylesheet_link_tag :application %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>

    <%= yield(:head) %>
  </head>

  <body>
    <%= image_tag 'default_favicon.png', class: 'js-default-favicon', style: 'display: none;' %>

    <div class="container">
      <div class="row ">
        <h1 class="col-xs-4"><%= link_to 'Daily Sites', '/' %></h1>
        <div class="col-xs-8 login-info">
          <% if logged_in? %>
            <div class="pull-right">
              Signed in as <%= current_user.name %>.

              <%= link_to 'View profile', profile_path, class: 'btn btn-default' %>
              <%= link_to 'Sign out', sign_out_path, data: {method: :delete}, class: 'btn btn-default' %>
            </div>
          <% end %>
        </div>
      </div>

      <% if flash.key?(:error) %>
        <div class="alert alert-dismissible alert-danger" role="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% end %>

      <% if flash.key?(:notice) %>
        <div class="alert alert-dismissible alert-success" role="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <hr>

      <%= yield %>
    </div>
  </body>
</html>